# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"  # bump GHA packages
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "dependabot: "
      # include: ""  # currently only "scope" is allowed
    open-pull-requests-limit: 1  # this is per ecosystem

  - package-ecosystem: "pip"  # bump python deps
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "dependabot: "
      # include: ""  # currently only "scope" is allowed
    allow:
      - dependency-type: "direct"  # all explicitly defined dependencies
    versioning-strategy: increase-if-necessary  # this allows not-exactly-equals pip notations (~=, ==v1.2.*, etc.)
    open-pull-requests-limit: 1  # this is per ecosystem
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
