version: 2

jobs:

    test:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox
                tox -vv

    test-w-telemetry:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox wipac-telemetry
                tox -vv

    pycycle:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox pycycle
                tox --notest -vv
                . .tox/py/bin/activate
                pycycle --here --verbose


workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - test-w-telemetry
            - pycycle
