name: Add PR/Issue to Project


on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    if: ${{ github.actor != 'dependabot[bot]' }} # dependabot cannot access token
    runs-on: ubuntu-latest
    steps:
      - uses: WIPACrepo/wipac-dev-project-action@v1.0
        with:
          github_token: ${{ secrets.ORG_PROJECT_TOKEN }}
          organization: WIPACrepo
          project_number: 6
